import {
  Globe, Rocket, BarChart3, Wrench, BookText, BadgeDollarSign,
  ScrollText, Pencil, FileText, Mic, MonitorPlay, Megaphone,
  Smartphone, DoorOpen, Settings as Cog, Mail, Image as Img,
  Newspaper, FlaskConical, Briefcase, Ticket, Receipt, ListTodo,
  Network, Map, Utensils, Heart, User, Layout, Send, Scale, Compass,
  Clock, Search, Palette, MessageSquare, HelpCircle, Lock, Bell,
  UserCircle, ShoppingCart, Table, Columns,
  type LucideIcon,
} from 'lucide-react';

const MAP: Record<string, LucideIcon> = {
  'web-prototype':    Globe,
  'saas-landing':     Rocket,
  'dashboard':        BarChart3,
  'admin-console':    Wrench,
  'docs-portal':      BookText,
  'pricing-page':     BadgeDollarSign,
  'changelog':        ScrollText,
  'blog-post':        Pencil,
  'one-pager':        FileText,
  'pitch-deck':       Mic,
  'product-deck':     MonitorPlay,
  'all-hands-deck':   Megaphone,
  'mobile-app':       Smartphone,
  'mobile-onboarding': DoorOpen,
  'mobile-settings':  Cog,
  'email-template':   Mail,
  'social-card':      Img,
  'press-kit':        Newspaper,
  'case-study':       FlaskConical,
  'job-listing':      Briefcase,
  'event-page':       Ticket,
  'invoice':          Receipt,
  'receipt':          Receipt,
  'pm-spec':          ListTodo,
  'rfc':              ListTodo,
  'system-diagram':   Network,
  'menu-card':        Utensils,
  'wedding-invite':   Heart,
  'resume':           User,
  'portfolio':        Layout,
  'newsletter':       Send,
  'comparison':       Scale,
  '404':              Compass,
  'waitlist':         Clock,
  'feature-page':     Search,
  'style-guide':      Palette,
  'testimonials':     MessageSquare,
  'faq-page':         HelpCircle,
  'login-page':       Lock,
  'notification-center': Bell,
  'profile-page':     UserCircle,
  'checkout':         ShoppingCart,
  'data-table':       Table,
  'kanban':           Columns,
};

export function iconForSkill(id: string): LucideIcon {
  return MAP[id] ?? Map;
}
