// Static skills + design systems + prompt templates + visual directions.
// Authored fresh; portable. Renderer fetches via IPC.
/* ─── SKILLS ──────────────────────────────────────────────────────────── */
const Q_BASE = [
    { id: 'audience', label: 'Who is this for?', type: 'text', placeholder: 'e.g. mid-market design leads' },
    { id: 'tone', label: 'Tone', type: 'select', options: ['minimal', 'editorial', 'energetic', 'technical', 'playful', 'austere'] },
    { id: 'scope', label: 'What must be present?', type: 'textarea' },
    { id: 'brand', label: 'Brand notes (optional)', type: 'textarea' },
];
const skills = [
    {
        id: 'web-prototype', name: 'Web Prototype', category: 'web', emoji: '🌐',
        blurb: 'Client-ready single-page website — token-driven CSS, full sections, no filler.',
        primer: 'Build a complete client-ready single-page site in one self-contained HTML file. Use a single <style> block with :root CSS tokens from the active design system — not Tailwind CDN. Minimum: sticky nav, hero, services/features grid, gallery or showcase, CTA band, footer. Header must use flex-wrap so logo, links, and CTA never overflow (min-width:0 on children). Serif display headlines, inline SVG icons (no emoji), .ph-img for photos. Copy must be specific to the user brief — no lorem, no invented metrics, no generic AI-startup gradients.',
        questions: Q_BASE,
    },
    {
        id: 'saas-landing', name: 'SaaS Landing', category: 'web', emoji: '🚀',
        blurb: 'Conversion-tuned landing with social proof + pricing.',
        primer: 'Hero with primary CTA above the fold (use split-hero or centered-hero pattern), social-proof row (logo strip or metric counters with staggered entrance animation), three-column feature grid (icon + heading + 2-line description, hover: elevation-2 + translateY(-2px)), pricing table (3 tiers, center highlighted at scale 1.02, monthly/annual toggle), testimonial block (featured pull-quote with realistic names and roles), FAQ accordion, footer. Add 2–3 gradient orbs behind the hero. Use dark/light theme tokens.',
        questions: [
            { id: 'product', label: 'Product name + 1-line pitch', type: 'text' },
            { id: 'audience', label: 'Target customer', type: 'text' },
            { id: 'tiers', label: 'Pricing tiers', type: 'textarea', placeholder: 'Starter $19 / Pro $49 / Team $99' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['confident', 'friendly', 'technical', 'playful'] },
        ],
    },
    {
        id: 'dashboard', name: 'Dashboard', category: 'web', emoji: '📊',
        blurb: 'KPI tiles, charts, table — single screen.',
        primer: 'Top KPI strip (4 tiles with staggered entrance animation, elevation-1 cards, accent left-border for trend indicator), 2 chart panels (CSS-only bar/line charts with gradient fills and grid-dot background), filterable data table (zebra rows, sticky header, hover: row highlight). Use dark/light theme tokens throughout. Realistic metrics: "$2.4M revenue", "12,847 users", "99.97% uptime".',
        questions: [
            { id: 'product', label: 'What is being measured?', type: 'text' },
            { id: 'kpis', label: '4 KPIs (comma-separated)', type: 'text' },
            { id: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'] },
        ],
    },
    {
        id: 'admin-console', name: 'Admin Console', category: 'web', emoji: '🛠️',
        blurb: 'Sidebar nav, resource table, side-panel detail.',
        primer: 'Left nav + main table + right detail drawer. Pagination, search, bulk-action bar. Empty + loading + error states. Use elevation-1 on cards, elevation-3 on the detail drawer. Dark/light theme tokens for all surfaces. Entrance animations on panel open. Realistic content for table rows — diverse names, specific roles, plausible timestamps.',
        questions: Q_BASE,
    },
    {
        id: 'docs-portal', name: 'Docs Portal', category: 'web', emoji: '📚',
        blurb: 'Three-column docs: nav, content, on-this-page.',
        primer: 'Left tree nav, center long-form Markdown render, right TOC. Code blocks with copy button, dark/light theme toggle, search affordance. Use elevation-1 on code blocks, radius-md on cards. Entrance animation on page transition. Realistic headings and code examples — no placeholder text.',
        questions: Q_BASE,
    },
    {
        id: 'pricing-page', name: 'Pricing Page', category: 'web', emoji: '💵',
        blurb: 'Three-tier pricing — Free / Standard / Premium cards, comparison, FAQ.',
        primer: 'Build a focused pricing page (not a full marketing site). Never ask clarifying questions — infer product name, tone, and tier copy from the brief. Claude-style three-column plan cards on a dark token-driven canvas. Default tier names: Free, Standard, Premium — unless the brief specifies different names/prices. One self-contained HTML file, inline CSS only, design-system tokens. Min: compact header, hero title, optional monthly/annual toggle, 3 plan cards, feature comparison table, FAQ, slim footer.',
        questions: [
            { id: 'product', label: 'Product name', type: 'text' },
            { id: 'tiers', label: 'Custom tiers (optional)', type: 'textarea', placeholder: 'Leave blank for Free / Standard / Premium defaults' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['confident', 'friendly', 'editorial'] },
        ],
    },
    {
        id: 'changelog', name: 'Changelog', category: 'web', emoji: '🗒️',
        blurb: 'Versioned release notes.',
        primer: 'Reverse-chronological entries, semver tags, type chips (feat/fix/perf), inline screenshots as colored blocks. Use entrance animation on each entry reveal. Elevation-1 on entry cards. Dark/light theme tokens. Realistic version numbers and dates — "v2.4.0 · March 2024", specific feature descriptions.',
        questions: [
            { id: 'product', label: 'Product', type: 'text' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['terse', 'editorial', 'enthusiastic'] },
        ],
    },
    {
        id: 'blog-post', name: 'Blog Post', category: 'doc', emoji: '✍️',
        blurb: 'Long-form editorial article.',
        primer: 'Title, deck, hero block, drop cap, pull-quotes, sidenotes, footer-bio. Read-time + share row. Clear typography hierarchy — display heading, body at 18px/1.7, caption for metadata. Dark/light theme tokens. Entrance animation on scroll for pull-quotes. Realistic content — benefit-driven headline, specific author name and role, plausible publication date.',
        questions: [
            { id: 'topic', label: 'Topic', type: 'text' },
            { id: 'angle', label: 'Angle', type: 'text' },
            { id: 'voice', label: 'Voice', type: 'select', options: ['analytical', 'narrative', 'opinionated', 'first-person'] },
        ],
    },
    {
        id: 'one-pager', name: 'One-pager', category: 'doc', emoji: '📄',
        blurb: 'Crisp printable memo.',
        primer: 'Title, executive summary, three sections, one callout (elevation-1, accent left-border), one comparison table, takeaway. Print-friendly layout with @media print styles. Dark/light theme tokens. Clear typography hierarchy. Realistic content — specific metrics, named stakeholders, plausible dates.',
        questions: [
            { id: 'topic', label: 'Topic', type: 'text' },
            { id: 'reader', label: 'Reader', type: 'text', placeholder: 'CFO / Eng VP / customer' },
        ],
    },
    {
        id: 'pitch-deck', name: 'Pitch Deck', category: 'deck', emoji: '🎤',
        blurb: '10-slide investor deck.',
        primer: '10 full-viewport slides: title, problem, insight, solution, demo, market, traction, business, team, ask. Slide footer: deck title · slide N. Display typography with tight tracking for slide headings. Gradient orbs as decorative backgrounds on title and ask slides. Entrance animation on each slide (fade 400ms). Realistic metrics: "$2.4M ARR", "340% YoY growth". Dark/light theme tokens.',
        questions: [
            { id: 'company', label: 'Company name', type: 'text' },
            { id: 'sector', label: 'Sector / one-liner', type: 'text' },
            { id: 'stage', label: 'Stage', type: 'select', options: ['pre-seed', 'seed', 'series A', 'series B'] },
            { id: 'ask', label: 'Ask', type: 'text', placeholder: '$2M for 18mo runway' },
        ],
    },
    {
        id: 'product-deck', name: 'Product Deck', category: 'deck', emoji: '📽️',
        blurb: '12-slide product walkthrough.',
        primer: 'Cover, why-now, current pain, product map, 4 feature slides, integrations, security, pricing, contact. Display typography for slide titles. Gradient orbs on cover slide. Entrance animation on content blocks (staggered fade-in). Elevation-1 on feature cards within slides. Realistic product names and metrics. Dark/light theme tokens.',
        questions: Q_BASE,
    },
    {
        id: 'all-hands-deck', name: 'All-hands Deck', category: 'deck', emoji: '🗣️',
        blurb: 'Internal update deck — wins, asks, plan.',
        primer: '8 slides: cover, last-quarter wins, metrics, what hurt, what we learned, plan next quarter, asks, q&a. Display typography for slide headings. Gradient background on cover. Entrance animation on metric reveals (staggered count-up). Elevation-1 on metric cards. Realistic team metrics and dates — "Q1 2024", "$1.2M closed". Dark/light theme tokens.',
        questions: Q_BASE,
    },
    {
        id: 'mobile-app', name: 'Mobile App Screen', category: 'mobile', emoji: '📱',
        blurb: 'Single mobile screen, phone-frame ready.',
        primer: '390×844 viewport. Header, content, bottom tab bar. No horizontal scroll. Touch targets ≥44px. Use elevation-1 on cards, entrance animation on screen transition (slide-in 300ms ease-out). Dark/light theme tokens for all surfaces. Realistic content — specific app data, diverse names, plausible timestamps like "2h ago".',
        questions: [
            { id: 'screen', label: 'Which screen?', type: 'text', placeholder: 'home / detail / settings' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['playful', 'minimal', 'editorial', 'utilitarian'] },
        ],
    },
    {
        id: 'mobile-onboarding', name: 'Mobile Onboarding', category: 'mobile', emoji: '🚪',
        blurb: '3-step onboarding carousel.',
        primer: '3 phone screens stacked vertically inside a phone frame: welcome, value, signup. Pagination dots, skip affordance. Entrance animation on each step (fade + translateX). Dark/light theme tokens. Realistic onboarding copy — benefit-driven headlines, specific feature descriptions, no placeholder text.',
        questions: Q_BASE,
    },
    {
        id: 'mobile-settings', name: 'Mobile Settings', category: 'mobile', emoji: '⚙️',
        blurb: 'iOS-style grouped settings list.',
        primer: 'Grouped list with section headers, chevrons, toggles, destructive row. Status bar + nav header. Touch targets ≥44px. Elevation-1 on grouped sections, radius-lg on group containers. Dark/light theme tokens. Entrance animation on section reveal. Realistic setting labels and user profile data — diverse name, specific email.',
        questions: Q_BASE,
    },
    {
        id: 'email-template', name: 'Email Template', category: 'media', emoji: '✉️',
        blurb: 'Transactional or marketing email.',
        primer: 'Inline-styled email-safe HTML, 600px wide centered. Header, hero, body, CTA (accent fill, radius-md), footer with unsubscribe. Clear typography hierarchy — display heading, body at 16px. Realistic content — specific product name, benefit-driven headline, named sender, plausible unsubscribe and company address.',
        questions: [
            { id: 'kind', label: 'Kind', type: 'select', options: ['welcome', 'announce', 'digest', 'receipt', 'reset'] },
            { id: 'tone', label: 'Tone', type: 'select', options: ['warm', 'sober', 'energetic'] },
        ],
    },
    {
        id: 'social-card', name: 'Social Card', category: 'media', emoji: '🪪',
        blurb: '1200×630 og:image preview.',
        primer: 'Single 1200×630 visual block with display title, byline, brand mark. Gradient orbs as decorative background. Bold typography hierarchy — display heading with tight tracking. Realistic content — specific article title, named author, plausible publication name.',
        questions: [
            { id: 'title', label: 'Title', type: 'text' },
            { id: 'kicker', label: 'Kicker (eyebrow)', type: 'text' },
        ],
    },
    {
        id: 'press-kit', name: 'Press Kit', category: 'web', emoji: '📰',
        blurb: 'Public-facing press resources page.',
        primer: 'Brand quote hero (centered-hero pattern), founder shot block, asset download grid (elevation-1 cards with hover elevation-2), boilerplate section, contact card. Add gradient orbs behind the hero. Dark/light theme tokens. Realistic company details and executive names.',
        questions: Q_BASE,
    },
    {
        id: 'case-study', name: 'Case Study', category: 'doc', emoji: '🔬',
        blurb: 'Customer story with metrics.',
        primer: 'Hero with logo + headline (centered-hero pattern), the challenge, the approach, three result tiles (elevation-1 with staggered entrance animation), quote with realistic attribution, what-next CTA. Dark/light theme tokens. Realistic metrics: "340% improvement", "$1.2M saved". Diverse customer name and specific role.',
        questions: [
            { id: 'customer', label: 'Customer', type: 'text' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['investigative', 'celebratory', 'analytical'] },
        ],
    },
    {
        id: 'job-listing', name: 'Job Listing', category: 'doc', emoji: '👔',
        blurb: 'Role page that sells the company.',
        primer: 'Role title, team section, what-you-do bullets, requirements, benefits, equal-opportunity statement, apply CTA (accent fill, radius-md). Dark/light theme tokens. Entrance animation on section reveal. Realistic content — specific company name, team details, concrete benefits like "$5K learning budget", diverse hiring manager name.',
        questions: [
            { id: 'role', label: 'Role', type: 'text' },
            { id: 'team', label: 'Team', type: 'text' },
        ],
    },
    {
        id: 'event-page', name: 'Event Page', category: 'web', emoji: '🎟️',
        blurb: 'Single-event landing with agenda + RSVP.',
        primer: 'Hero (centered-hero pattern with title, date, place), agenda timeline with entrance animation (staggered reveal), speaker grid (elevation-1 cards with avatar blocks), RSVP form (radius-md inputs), sponsor row. Gradient orbs behind hero. Dark/light theme tokens. Realistic content — specific event name, diverse speaker names, plausible schedule.',
        questions: [
            { id: 'event', label: 'Event name', type: 'text' },
            { id: 'when', label: 'When', type: 'text' },
            { id: 'where', label: 'Where', type: 'text' },
        ],
    },
    {
        id: 'invoice', name: 'Invoice', category: 'doc', emoji: '🧾',
        blurb: 'Printable invoice document.',
        primer: 'Issuer + bill-to blocks, line-item table (elevation-1), subtotal/tax/total stack, payment terms footer. Print-friendly with @media print styles. Dark/light theme tokens. Realistic content — plausible company names, specific line items, realistic pricing, proper date formatting "Jan 15, 2024".',
        questions: Q_BASE,
    },
    {
        id: 'receipt', name: 'Receipt', category: 'doc', emoji: '📑',
        blurb: 'Order confirmation card.',
        primer: 'Compact card (elevation-2, radius-lg): brand header, order id, line items, totals, support contact. Dark/light theme tokens. Realistic content — plausible order number "#ORD-28471", specific product names, realistic pricing, timestamp "March 15, 2024 at 2:34 PM".',
        questions: Q_BASE,
    },
    {
        id: 'pm-spec', name: 'Product Spec', category: 'doc', emoji: '🗂️',
        blurb: 'PM-ready spec memo.',
        primer: 'Problem, users, goals/non-goals, success metrics, design sketch (described), open questions, milestones. Clear typography hierarchy with section numbering. Dark/light theme tokens. Elevation-1 on callout boxes. Realistic content — specific feature name, plausible success metrics like "reduce churn by 15%", named stakeholders.',
        questions: [
            { id: 'feature', label: 'Feature', type: 'text' },
            { id: 'audience', label: 'Audience', type: 'text' },
        ],
    },
    {
        id: 'rfc', name: 'RFC', category: 'doc', emoji: '📐',
        blurb: 'Engineering RFC document.',
        primer: 'Context, proposal, alternatives considered, risks, rollout plan, open questions, decision log table (elevation-1). Dark/light theme tokens. Clear typography hierarchy with numbered sections. Realistic content — specific system names, plausible timelines, named authors and reviewers.',
        questions: Q_BASE,
    },
    {
        id: 'system-diagram', name: 'System Diagram', category: 'system', emoji: '🧭',
        blurb: 'Boxes-and-arrows architecture diagram (HTML/SVG).',
        primer: 'Single SVG diagram with labelled nodes and edges, legend, swimlanes if useful. No external assets. Dark/light theme tokens for node fills and edge colors. Elevation-1 shadow on node boxes. Realistic content — specific service names like "API Gateway", "Auth Service", plausible data flow labels.',
        questions: [
            { id: 'system', label: 'System', type: 'text' },
            { id: 'depth', label: 'Depth', type: 'select', options: ['c1-context', 'c2-container', 'c3-component'] },
        ],
    },
    {
        id: 'menu-card', name: 'Menu Card', category: 'media', emoji: '🍽️',
        blurb: 'Restaurant or product menu.',
        primer: 'Print-style menu with sections, items, prices, footnotes. Editorial type, generous whitespace. Clear typography hierarchy — display serif for restaurant name, body for items. Dark/light theme tokens. Realistic content — plausible restaurant name, specific dishes with descriptions, realistic pricing like "$18", "$24".',
        questions: Q_BASE,
    },
    {
        id: 'wedding-invite', name: 'Invitation', category: 'media', emoji: '💌',
        blurb: 'Single-page event invitation.',
        primer: 'Names, date, place, RSVP affordance, ornamental rule. Display serif with elegant tracking. Single-page A5. Gradient orbs as subtle decorative background at low opacity. Dark/light theme tokens. Realistic content — diverse couple names, specific venue, plausible date.',
        questions: Q_BASE,
    },
    {
        id: 'resume', name: 'Résumé', category: 'doc', emoji: '👤',
        blurb: 'Single-page resume.',
        primer: 'Header with name + role + contact strip. Two-column body: left timeline (work, edu), right summary + skills + projects. Print-friendly with @media print styles. Dark/light theme tokens. Clear typography hierarchy. Realistic content — diverse name, specific companies and roles, plausible dates and achievements.',
        questions: [
            { id: 'role', label: 'Target role', type: 'text' },
            { id: 'years', label: 'Years experience', type: 'text' },
        ],
    },
    {
        id: 'portfolio', name: 'Portfolio Site', category: 'web', emoji: '🖼️',
        blurb: 'Personal portfolio.',
        primer: 'Hero with name + role (split-hero pattern), work grid (6 projects, color-block thumbnails with elevation-1, hover: elevation-2 + scale), about section, contact. Entrance animations on scroll. Gradient orbs as decorative background. Dark/light theme tokens. Realistic project names and descriptions.',
        questions: Q_BASE,
    },
    {
        id: 'newsletter', name: 'Newsletter Issue', category: 'doc', emoji: '📰',
        blurb: 'Single newsletter issue.',
        primer: 'Issue header, lede, three short sections, link list, sign-off, unsubscribe footer. Dark/light theme tokens. Clear typography hierarchy — display heading for issue title, body for content. Entrance animation on section reveal. Realistic content — specific issue number, plausible links, named editor.',
        questions: Q_BASE,
    },
    {
        id: 'comparison', name: 'Comparison Page', category: 'web', emoji: '⚖️',
        blurb: 'Vs-page comparing two offerings.',
        primer: 'Hero with both product names (centered-hero pattern), feature table (yes/no/partial chips, elevation-1 rows), per-feature paragraph blocks, CTA. Dark/light theme tokens. Realistic product names and feature descriptions. Entrance animation on table rows.',
        questions: [
            { id: 'us', label: 'Us', type: 'text' },
            { id: 'them', label: 'Them', type: 'text' },
        ],
    },
    {
        id: '404', name: '404 Page', category: 'web', emoji: '🧭',
        blurb: 'Friendly not-found page.',
        primer: 'Big display number with text-glow effect in dark mode, sentence of empathy, list of likely-useful links, search input. Gradient orbs as decorative background. Entrance animation on the display number. Dark/light theme tokens. Realistic link suggestions.',
        questions: Q_BASE,
    },
    {
        id: 'waitlist', name: 'Waitlist / Coming Soon', category: 'web', emoji: '⏳',
        blurb: 'Pre-launch teaser with email capture.',
        primer: 'Full-viewport hero (centered-hero pattern) with product name, one-liner, email capture form, social proof counter with staggered count-up entrance animation. CSS-only animated gradient background. Gradient orbs behind content. Dark/light theme tokens. Realistic social proof: "12,847 on the waitlist".',
        questions: [
            { id: 'product', label: 'Product name', type: 'text' },
            { id: 'pitch', label: 'One-line pitch', type: 'text' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['mysterious', 'confident', 'playful', 'minimal'] },
        ],
    },
    {
        id: 'feature-page', name: 'Feature Deep-dive', category: 'web', emoji: '🔍',
        blurb: 'Single-feature marketing page with demo.',
        primer: 'Hero with feature name + benefit (split-hero pattern), animated demo area (CSS-only), three supporting points with icon grid layout, comparison before/after, testimonial with realistic name and role, CTA. Entrance animations on scroll. Gradient orbs. Dark/light theme tokens.',
        questions: [
            { id: 'feature', label: 'Feature name', type: 'text' },
            { id: 'benefit', label: 'Key benefit', type: 'text' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['technical', 'friendly', 'bold'] },
        ],
    },
    {
        id: 'style-guide', name: 'Style Guide', category: 'doc', emoji: '🎨',
        blurb: 'Living brand style guide page.',
        primer: 'Color palette grid with hex/oklch values, typography scale specimen, spacing scale, button states, form elements, icon usage, do/don\'t examples. Dark/light theme tokens with live preview of both modes. Elevation-1 on specimen cards. Entrance animation on section reveal. Realistic brand name and specific design token values.',
        questions: [
            { id: 'brand', label: 'Brand name', type: 'text' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['minimal', 'editorial', 'technical'] },
        ],
    },
    {
        id: 'testimonials', name: 'Testimonials Wall', category: 'web', emoji: '💬',
        blurb: 'Social proof wall with quotes and avatars.',
        primer: 'Masonry or grid layout of testimonial cards (elevation-1, hover: elevation-2) with avatar blocks (colored circle with initials), name, role, company, quote. Star ratings optional. Filter by category. Entrance animation staggered on cards. Dark/light theme tokens. Realistic diverse names and specific praise.',
        questions: Q_BASE,
    },
    {
        id: 'faq-page', name: 'FAQ Page', category: 'web', emoji: '❓',
        blurb: 'Accordion FAQ with search.',
        primer: 'Search bar at top, categorized accordion sections (smooth expand with max-height transition), anchor links, contact CTA at bottom. Elevation-1 on accordion cards. Entrance animation on section reveal. Dark/light theme tokens. Realistic questions and detailed answers — no placeholder text.',
        questions: [
            { id: 'product', label: 'Product', type: 'text' },
            { id: 'categories', label: 'FAQ categories', type: 'textarea' },
        ],
    },
    {
        id: 'login-page', name: 'Login / Signup', category: 'web', emoji: '🔐',
        blurb: 'Auth page with split layout.',
        primer: 'Split layout: left panel with gradient orbs and decorative geometric shapes, right panel with form (elevation-2 card, radius-lg). Email + password fields, social login buttons, forgot password link, toggle login/signup. Dark/light theme tokens. Entrance animation on form card. Realistic product name.',
        questions: [
            { id: 'product', label: 'Product name', type: 'text' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['minimal', 'friendly', 'corporate', 'playful'] },
        ],
    },
    {
        id: 'notification-center', name: 'Notification Center', category: 'web', emoji: '🔔',
        blurb: 'Notification feed with filters.',
        primer: 'Slide-out panel or page with notification cards (elevation-1, unread: accent left-border), read/unread states, category filters, mark-all-read, empty state with decorative illustration. Entrance animation staggered on cards. Dark/light theme tokens. Realistic notifications with diverse names and relative timestamps.',
        questions: Q_BASE,
    },
    {
        id: 'profile-page', name: 'User Profile', category: 'web', emoji: '👤',
        blurb: 'User profile with activity feed.',
        primer: 'Avatar + cover area (gradient orbs as cover background), stats row with staggered count-up entrance animation, tab navigation (activity/projects/settings), activity feed cards (elevation-1). Dark/light theme tokens. Realistic user data — diverse name, specific role, plausible metrics.',
        questions: Q_BASE,
    },
    {
        id: 'checkout', name: 'Checkout Flow', category: 'web', emoji: '🛒',
        blurb: 'Multi-step checkout page.',
        primer: 'Progress stepper, order summary sidebar (elevation-2), shipping form, payment form with card input (radius-md inputs), review step, place-order CTA. Trust badges. Dark/light theme tokens. Entrance animation on step transitions. Realistic product names and pricing.',
        questions: [
            { id: 'product', label: 'What is being sold?', type: 'text' },
            { id: 'tone', label: 'Tone', type: 'select', options: ['minimal', 'trustworthy', 'premium'] },
        ],
    },
    {
        id: 'data-table', name: 'Data Table', category: 'web', emoji: '📋',
        blurb: 'Rich data table with sort, filter, pagination.',
        primer: 'Toolbar with search + filters + bulk actions, sortable column headers, row selection checkboxes, inline status badges (radius-full pills), pagination footer, responsive collapse. Elevation-1 on table container. Dark/light theme tokens. Realistic data rows with diverse names, specific roles, plausible dates.',
        questions: [
            { id: 'data', label: 'What data?', type: 'text' },
            { id: 'columns', label: 'Key columns', type: 'textarea' },
        ],
    },
    {
        id: 'kanban', name: 'Kanban Board', category: 'web', emoji: '📌',
        blurb: 'Drag-ready kanban columns.',
        primer: 'Horizontal scrolling columns (To Do, In Progress, Done, etc.), cards with title + assignee + priority badge (elevation-1, hover: elevation-2), add-card affordance, column count badges. Entrance animation on card add. Dark/light theme tokens. Realistic task titles and diverse assignee names.',
        questions: [
            { id: 'domain', label: 'Domain', type: 'text', placeholder: 'project management / hiring / support' },
            { id: 'columns', label: 'Column names', type: 'text' },
        ],
    },
];
const SEED_SYSTEMS = [
    { id: 'ember', name: 'Ember', vibe: 'Warm editorial, ink + amber', font: 'Inter / Instrument Serif', base: 0.18, hue: 50, sat: 0.18 },
    { id: 'arctic', name: 'Arctic', vibe: 'Cool, precise, glassy', font: 'Inter / IBM Plex Sans', base: 0.97, hue: 240, sat: 0.13, light: true },
    { id: 'graphite', name: 'Graphite', vibe: 'Editorial newsroom, monochrome', font: 'Söhne / Inter', base: 0.10, hue: 0, sat: 0.00 },
    { id: 'aurora', name: 'Aurora', vibe: 'Vivid gradient, bold display', font: 'Geist / Inter', base: 0.16, hue: 320, sat: 0.20, accent2Hue: 200 },
    { id: 'paper', name: 'Paper', vibe: 'Soft beige, longform', font: 'Instrument Serif / Inter', base: 0.97, hue: 30, sat: 0.16, light: true },
    { id: 'forge', name: 'Forge', vibe: 'Industrial, dense, mono accent', font: 'JetBrains Mono / Inter', base: 0.14, hue: 145, sat: 0.16 },
    { id: 'oxide', name: 'Oxide', vibe: 'Rust on slate, terminal-like', font: 'IBM Plex Mono / Inter', base: 0.16, hue: 25, sat: 0.20 },
    { id: 'mono', name: 'Mono', vibe: 'Pure tonal grayscale', font: 'Inter / Inter', base: 0.96, hue: 0, sat: 0.00, light: true },
    { id: 'velvet', name: 'Velvet', vibe: 'Plum and rose, soft', font: 'Fraunces / Inter', base: 0.18, hue: 350, sat: 0.16 },
    { id: 'matcha', name: 'Matcha', vibe: 'Quiet green, warm muted', font: 'Söhne / Inter', base: 0.94, hue: 145, sat: 0.10, light: true },
    { id: 'cobalt', name: 'Cobalt', vibe: 'Deep blue, professional', font: 'Inter / Inter', base: 0.18, hue: 250, sat: 0.18 },
    { id: 'tabula', name: 'Tabula', vibe: 'Newsprint, editorial restraint', font: 'PT Serif / Inter', base: 0.97, hue: 60, sat: 0.04, light: true },
    { id: 'neon', name: 'Neon', vibe: 'Black + electric lime', font: 'JetBrains Mono / Inter', base: 0.10, hue: 130, sat: 0.30 },
    { id: 'beach', name: 'Beach', vibe: 'Sand, sea, sun', font: 'Inter / Inter', base: 0.96, hue: 200, sat: 0.16, light: true, accent2Hue: 35 },
    { id: 'noir', name: 'Noir', vibe: 'Cinematic black with red hint', font: 'Inter / Playfair Display', base: 0.10, hue: 12, sat: 0.18 },
    { id: 'paloma', name: 'Paloma', vibe: 'Dove gray, gentle, restrained', font: 'Inter / Inter', base: 0.92, hue: 240, sat: 0.04, light: true },
    { id: 'orchard', name: 'Orchard', vibe: 'Fruit-stand colors, friendly', font: 'Inter / Inter', base: 0.96, hue: 12, sat: 0.14, light: true, accent2Hue: 145 },
    { id: 'ink', name: 'Ink', vibe: 'Dark indigo, low chroma', font: 'Inter / Inter', base: 0.14, hue: 260, sat: 0.10 },
    { id: 'mint', name: 'Mint', vibe: 'Fresh, high contrast', font: 'Inter / Inter', base: 0.97, hue: 165, sat: 0.16, light: true },
    { id: 'dune', name: 'Dune', vibe: 'Desert sand, sun-bleached', font: 'Inter / Inter', base: 0.93, hue: 75, sat: 0.10, light: true },
    { id: 'lagoon', name: 'Lagoon', vibe: 'Tropical aqua, vivid', font: 'Inter / Inter', base: 0.18, hue: 195, sat: 0.18 },
    { id: 'cardinal', name: 'Cardinal', vibe: 'Wine red, ornate', font: 'Fraunces / Inter', base: 0.20, hue: 12, sat: 0.20 },
    { id: 'glass', name: 'Glass', vibe: 'Frosted glassmorphism', font: 'Inter / Inter', base: 0.16, hue: 220, sat: 0.10 },
    { id: 'kraft', name: 'Kraft', vibe: 'Recycled paper, warm', font: 'Inter / Inter', base: 0.90, hue: 40, sat: 0.10, light: true },
    { id: 'midnight', name: 'Midnight', vibe: 'Deep navy with cyan accent', font: 'Inter / Inter', base: 0.12, hue: 230, sat: 0.16, accent2Hue: 195 },
    { id: 'sakura', name: 'Sakura', vibe: 'Pink, gentle, hopeful', font: 'Fraunces / Inter', base: 0.96, hue: 350, sat: 0.10, light: true },
    { id: 'umbra', name: 'Umbra', vibe: 'Deep brown, archival', font: 'Fraunces / Inter', base: 0.18, hue: 30, sat: 0.10 },
    { id: 'civic', name: 'Civic', vibe: 'Government formal, quiet blue', font: 'Inter / Inter', base: 0.96, hue: 220, sat: 0.10, light: true },
    { id: 'arcade', name: 'Arcade', vibe: 'Retro game UI, magenta + cyan', font: 'JetBrains Mono / Inter', base: 0.12, hue: 320, sat: 0.22, accent2Hue: 195 },
    { id: 'fjord', name: 'Fjord', vibe: 'Slate blue, scandinavian', font: 'Inter / Inter', base: 0.94, hue: 220, sat: 0.06, light: true },
    { id: 'molten', name: 'Molten', vibe: 'Red-hot metal, dangerous', font: 'Inter / Inter', base: 0.10, hue: 24, sat: 0.22 },
    { id: 'helix', name: 'Helix', vibe: 'Bio-tech, soft mint + cobalt', font: 'Inter / Inter', base: 0.96, hue: 165, sat: 0.10, light: true, accent2Hue: 250 },
    { id: 'opal', name: 'Opal', vibe: 'Iridescent, pearl-pastel', font: 'Inter / Inter', base: 0.95, hue: 280, sat: 0.08, light: true, accent2Hue: 200 },
    { id: 'soot', name: 'Soot', vibe: 'Smoky black, low key', font: 'Inter / Inter', base: 0.08, hue: 30, sat: 0.04 },
    { id: 'plaster', name: 'Plaster', vibe: 'Off-white walls, restrained', font: 'Inter / Söhne', base: 0.94, hue: 60, sat: 0.04, light: true },
    { id: 'eclipse', name: 'Eclipse', vibe: 'Deep purple corona', font: 'Inter / Inter', base: 0.10, hue: 290, sat: 0.18 },
    { id: 'kelp', name: 'Kelp', vibe: 'Wet seaweed, deep green', font: 'Inter / Inter', base: 0.16, hue: 150, sat: 0.12 },
    { id: 'mango', name: 'Mango', vibe: 'Tropical orange + leaf green', font: 'Inter / Inter', base: 0.96, hue: 35, sat: 0.18, light: true, accent2Hue: 145 },
    { id: 'grove', name: 'Grove', vibe: 'Forest green, earthy', font: 'Fraunces / Inter', base: 0.16, hue: 130, sat: 0.10 },
    { id: 'pebble', name: 'Pebble', vibe: 'River stone, neutral warm', font: 'Inter / Inter', base: 0.92, hue: 30, sat: 0.04, light: true },
    { id: 'ember-ii', name: 'Ember II', vibe: 'Ember inverted, light + amber', font: 'Inter / Instrument Serif', base: 0.96, hue: 30, sat: 0.16, light: true },
    { id: 'cosmos', name: 'Cosmos', vibe: 'Deep space, starfield', font: 'Inter / Inter', base: 0.08, hue: 240, sat: 0.16, accent2Hue: 320 },
    { id: 'powder', name: 'Powder', vibe: 'Powder-blue snow', font: 'Inter / Inter', base: 0.96, hue: 210, sat: 0.06, light: true },
    { id: 'foundry', name: 'Foundry', vibe: 'Coal + spark orange', font: 'JetBrains Mono / Inter', base: 0.10, hue: 25, sat: 0.20 },
    { id: 'gilded', name: 'Gilded', vibe: 'Black + brushed gold', font: 'Fraunces / Inter', base: 0.10, hue: 70, sat: 0.16 },
    { id: 'iris', name: 'Iris', vibe: 'Cool violet, crisp', font: 'Inter / Inter', base: 0.97, hue: 270, sat: 0.10, light: true },
    { id: 'monsoon', name: 'Monsoon', vibe: 'Storm grey + lightning blue', font: 'Inter / Inter', base: 0.18, hue: 215, sat: 0.10, accent2Hue: 195 },
    { id: 'fresco', name: 'Fresco', vibe: 'Plaster + sun-baked clay', font: 'Fraunces / Inter', base: 0.94, hue: 25, sat: 0.10, light: true },
    { id: 'nori', name: 'Nori', vibe: 'Seaweed black-green', font: 'Inter / Inter', base: 0.14, hue: 155, sat: 0.06 },
    { id: 'parchment', name: 'Parchment', vibe: 'Aged paper, warm sepia', font: 'Instrument Serif / Inter', base: 0.94, hue: 50, sat: 0.10, light: true },
    { id: 'meridian', name: 'Meridian', vibe: 'Navigator, brass + navy', font: 'Inter / Fraunces', base: 0.16, hue: 220, sat: 0.14, accent2Hue: 60 },
    { id: 'ash', name: 'Ash', vibe: 'Cold ash, near-mono', font: 'Inter / Inter', base: 0.94, hue: 220, sat: 0.02, light: true },
    { id: 'currant', name: 'Currant', vibe: 'Berry red on cream', font: 'Fraunces / Inter', base: 0.95, hue: 0, sat: 0.16, light: true },
    { id: 'avocado', name: 'Avocado', vibe: 'Soft retro green-brown', font: 'Inter / Inter', base: 0.93, hue: 95, sat: 0.10, light: true },
    { id: 'denim', name: 'Denim', vibe: 'Workwear blue + tan', font: 'Inter / Inter', base: 0.95, hue: 220, sat: 0.10, light: true, accent2Hue: 35 },
    { id: 'agate', name: 'Agate', vibe: 'Banded mineral teal', font: 'Inter / Inter', base: 0.18, hue: 180, sat: 0.10 },
    { id: 'tea', name: 'Tea', vibe: 'Green tea + porcelain', font: 'Fraunces / Inter', base: 0.95, hue: 130, sat: 0.06, light: true },
    { id: 'briar', name: 'Briar', vibe: 'Deep wine + gold leaf', font: 'Fraunces / Inter', base: 0.16, hue: 350, sat: 0.18, accent2Hue: 60 },
    { id: 'porcelain', name: 'Porcelain', vibe: 'Eggshell + cobalt accents', font: 'Inter / Inter', base: 0.97, hue: 220, sat: 0.06, light: true },
    { id: 'bay', name: 'Bay', vibe: 'Bay-window blue, calm', font: 'Inter / Inter', base: 0.93, hue: 195, sat: 0.08, light: true },
    { id: 'plum', name: 'Plum', vibe: 'Saturated dark plum', font: 'Inter / Inter', base: 0.16, hue: 305, sat: 0.16 },
    { id: 'bronze', name: 'Bronze', vibe: 'Hammered bronze + cocoa', font: 'Fraunces / Inter', base: 0.16, hue: 35, sat: 0.12 },
    { id: 'bone', name: 'Bone', vibe: 'Pale ivory bone', font: 'Fraunces / Inter', base: 0.96, hue: 60, sat: 0.06, light: true },
    { id: 'copper', name: 'Copper', vibe: 'Patina copper + slate', font: 'Inter / Inter', base: 0.18, hue: 180, sat: 0.10, accent2Hue: 25 },
    { id: 'ferro', name: 'Ferro', vibe: 'Iron grey, magnetic blue', font: 'Inter / Inter', base: 0.14, hue: 220, sat: 0.10 },
    { id: 'lichen', name: 'Lichen', vibe: 'Stone wall green-grey', font: 'Inter / Inter', base: 0.94, hue: 110, sat: 0.05, light: true },
    { id: 'rouge', name: 'Rouge', vibe: 'Theater red, dim gold', font: 'Fraunces / Inter', base: 0.16, hue: 0, sat: 0.16, accent2Hue: 60 },
    { id: 'alpine', name: 'Alpine', vibe: 'Snow + pine + sky', font: 'Inter / Inter', base: 0.96, hue: 195, sat: 0.10, light: true, accent2Hue: 145 },
    { id: 'volcano', name: 'Volcano', vibe: 'Black sand + lava red', font: 'Inter / Inter', base: 0.10, hue: 12, sat: 0.22 },
    { id: 'concrete', name: 'Concrete', vibe: 'Brutalist grey, stamped', font: 'JetBrains Mono / Inter', base: 0.18, hue: 0, sat: 0.02 },
    { id: 'lemon', name: 'Lemon', vibe: 'High-vis yellow + black', font: 'Inter / Inter', base: 0.97, hue: 90, sat: 0.18, light: true },
    { id: 'lichee', name: 'Lichee', vibe: 'Lychee pink + bamboo', font: 'Inter / Inter', base: 0.96, hue: 350, sat: 0.10, light: true, accent2Hue: 130 },
];
function buildSystem(s) {
    const surfaceL = s.light ? Math.max(0.05, s.base - 0.05) : Math.min(0.92, s.base + 0.04);
    const fgL = s.light ? 0.18 : 0.95;
    const accentL = s.light ? 0.5 : 0.7;
    const mutedL = s.light ? 0.35 : 0.55;
    const sat = s.sat;
    const hue = s.hue;
    const acc2 = s.accent2Hue ?? (hue + 60) % 360;
    const swatches = [
        `oklch(${s.base.toFixed(2)} ${(sat * 0.1).toFixed(2)} ${hue})`,
        `oklch(${surfaceL.toFixed(2)} ${(sat * 0.2).toFixed(2)} ${hue})`,
        `oklch(${(s.light ? 0.6 : 0.85).toFixed(2)} ${(sat * 0.4).toFixed(2)} ${hue})`,
        `oklch(${accentL.toFixed(2)} ${sat.toFixed(2)} ${hue})`,
        `oklch(${(accentL - 0.1).toFixed(2)} ${(sat * 1.1).toFixed(2)} ${hue})`,
        `oklch(${(s.light ? 0.95 : 0.40).toFixed(2)} ${(sat * 0.3).toFixed(2)} ${acc2})`,
    ];
    const tokens = [
        { name: 'bg', value: `oklch(${s.base.toFixed(2)} ${(sat * 0.1).toFixed(2)} ${hue})` },
        { name: 'surface', value: `oklch(${surfaceL.toFixed(2)} ${(sat * 0.2).toFixed(2)} ${hue})` },
        { name: 'fg', value: `oklch(${fgL.toFixed(2)} ${(sat * 0.05).toFixed(2)} ${hue})` },
        { name: 'accent', value: `oklch(${accentL.toFixed(2)} ${sat.toFixed(2)} ${hue})` },
        { name: 'accent2', value: `oklch(${(accentL).toFixed(2)} ${sat.toFixed(2)} ${acc2})` },
        { name: 'muted', value: `oklch(${mutedL.toFixed(2)} ${(sat * 0.1).toFixed(2)} ${hue})` },
    ];
    return { id: s.id, name: s.name, vibe: s.vibe, font: s.font, swatches, tokens };
}
const systems = SEED_SYSTEMS.map(buildSystem);
/* ─── PROMPT TEMPLATES ────────────────────────────────────────────────── */
const promptTemplates = [
    // Image — product
    { id: 'img-product-hero', kind: 'image', name: 'Product Hero', blurb: 'Clean studio shot for hero', tags: ['product', 'hero'],
        body: 'Studio product shot of {product}, soft top-light, gentle gradient backdrop, pin-sharp focus, subtle floor reflection, 50mm lens, ultra-clean composition.' },
    { id: 'img-product-lifestyle', kind: 'image', name: 'Product Lifestyle', blurb: 'In-context lifestyle frame', tags: ['product', 'lifestyle'],
        body: 'Lifestyle frame: {product} naturally placed on a {surface}, late-afternoon window light, warm color grade, shallow depth of field, journalistic feel.' },
    { id: 'img-flatlay', kind: 'image', name: 'Flatlay', blurb: 'Top-down composition', tags: ['product', 'flatlay'],
        body: 'Top-down flatlay of {items}, neutral linen backdrop, soft directional shadow, tight grid composition, editorial styling.' },
    { id: 'img-poster', kind: 'image', name: 'Editorial Poster', blurb: 'Bold type meets photo', tags: ['poster', 'editorial'],
        body: 'Editorial poster: large display type "{title}" in deep ink, layered over a high-contrast monochrome photograph of {subject}, generous margins, off-white paper texture.' },
    { id: 'img-magazine-cover', kind: 'image', name: 'Magazine Cover', blurb: 'Cover-style portrait', tags: ['magazine', 'cover'],
        body: 'Magazine cover: studio portrait of {subject} looking off-camera, masthead "{title}" at top, two cover-line teasers, paper-stock grain.' },
    { id: 'img-startup-illu', kind: 'image', name: 'Startup Illustration', blurb: 'Soft 3D abstract', tags: ['illustration', 'web'],
        body: 'Abstract soft-3D illustration suggesting {concept}: rounded translucent forms, pastel gradient, subtle volumetric light, no text.' },
    { id: 'img-icon-set', kind: 'image', name: 'Icon Set Hero', blurb: 'Icons in grid', tags: ['icons'],
        body: 'A 3×3 grid of monochrome line icons related to {theme}, even stroke weight, isometric perspective, deep navy line on warm cream.' },
    { id: 'img-architecture', kind: 'image', name: 'Architecture Frame', blurb: 'Built environment shot', tags: ['architecture'],
        body: 'Architectural photograph of {building}, blue hour, long exposure, perfect verticals, large-format feel, deep shadows.' },
    { id: 'img-food-overhead', kind: 'image', name: 'Food Overhead', blurb: 'Restaurant menu plate', tags: ['food'],
        body: 'Overhead shot of {dish} on a hand-thrown ceramic plate, single soft light, dark wood table, micro-greens scattered, restaurant-menu styling.' },
    { id: 'img-team-portrait', kind: 'image', name: 'Team Portrait', blurb: 'Group press portrait', tags: ['team', 'press'],
        body: 'Press-kit team portrait of {n} people in {location}, natural light, candid posing, neutral wardrobe, narrow palette.' },
    { id: 'img-startup-hero-photo', kind: 'image', name: 'Hero Photograph', blurb: 'Hero photograph for landing', tags: ['hero', 'photo'],
        body: 'Cinematic hero photograph of {scene}, anamorphic look, gentle bloom, color graded toward teal-amber, ample negative space top-right.' },
    { id: 'img-app-screen-mock', kind: 'image', name: 'App Screen Mockup', blurb: 'Phone in hand mockup', tags: ['mockup'],
        body: 'A hand holding a phone showing the screen "{ui}", close crop, soft daylight, minimal background, clean studio gradient.' },
    { id: 'img-blueprint', kind: 'image', name: 'Blueprint', blurb: 'Technical blueprint feel', tags: ['technical'],
        body: 'Indigo blueprint-style line drawing of {object}, white lines on deep blue, faint grid, annotations and dimension marks.' },
    { id: 'img-watercolor', kind: 'image', name: 'Watercolor', blurb: 'Loose watercolor wash', tags: ['art'],
        body: 'Loose watercolor of {subject}, generous whitespace, bleed and granulation visible, restrained palette of three pigments.' },
    { id: 'img-risograph', kind: 'image', name: 'Risograph Print', blurb: 'Two-color riso poster', tags: ['poster', 'art'],
        body: 'Two-color risograph print of {subject}, fluorescent pink and federal blue, slight registration drift, halftone texture.' },
    { id: 'img-pixel-iso', kind: 'image', name: 'Isometric Pixel', blurb: 'Pixel-isometric scene', tags: ['pixel', 'isometric'],
        body: 'Isometric pixel-art scene of {subject}, 16-color palette, soft long shadows, no text, calm composition.' },
    { id: 'img-line-portrait', kind: 'image', name: 'Line Portrait', blurb: 'Single-line drawing', tags: ['art'],
        body: 'Single-line ink portrait of {subject} on cream paper, no shading, calligraphic confidence, faint pencil guide.' },
    { id: 'img-claymation', kind: 'image', name: 'Claymation Object', blurb: 'Stop-motion clay vibe', tags: ['3d'],
        body: 'Claymation-style {object}, fingerprint texture, stop-motion lighting, slight imperfections, single-color backdrop.' },
    { id: 'img-vapor', kind: 'image', name: 'Vaporwave', blurb: 'Retro CG vibe', tags: ['retro'],
        body: 'Vaporwave scene of {subject}: chrome lettering, sunset gradient, low-poly mountains, scanlines, retro-CG feel.' },
    { id: 'img-cyberpunk', kind: 'image', name: 'Cyberpunk Street', blurb: 'Wet neon street', tags: ['cyberpunk'],
        body: 'Rain-slick alley, neon signage in {language}, lone figure in long coat, deep cyan + magenta, cinematic anamorphic flares.' },
    { id: 'img-figure-skate', kind: 'image', name: 'Athlete in Motion', blurb: 'Frozen action', tags: ['sport'],
        body: 'High-speed frozen action shot of {athlete} mid-{motion}, arena lighting, motion-blurred crowd, sharp subject.' },
    { id: 'img-illustration-news', kind: 'image', name: 'Op-ed Illustration', blurb: 'Editorial illustration', tags: ['illustration'],
        body: 'Op-ed illustration about {topic}, restrained palette of three flat colors, conceptual metaphor, soft grain texture.' },
    { id: 'img-abstract-bg', kind: 'image', name: 'Abstract Background', blurb: 'Hero gradient backdrop', tags: ['background'],
        body: 'Abstract hero background: large soft gradient sphere over a deep canvas, faint film grain, gentle vignette, no subject.' },
    { id: 'img-pattern', kind: 'image', name: 'Repeatable Pattern', blurb: 'Tileable wallpaper', tags: ['pattern'],
        body: 'Tileable wallpaper pattern based on {motif}, two-color, hand-drawn lines, even visual weight, repeats cleanly.' },
    { id: 'img-style-frame', kind: 'image', name: 'Style Frame', blurb: 'Single style frame', tags: ['styleframe'],
        body: 'Single film style-frame depicting {scene}, art-direction reference quality, color script intent, no UI overlays.' },
    { id: 'img-anatomy', kind: 'image', name: 'Anatomy Illustration', blurb: 'Vintage scientific plate', tags: ['illustration'],
        body: 'Vintage scientific plate of {subject}, hand-rendered, sepia ink on aged paper, latin annotations.' },
    { id: 'img-cap-of-flag', kind: 'image', name: 'Brand Banner', blurb: 'Wordmark banner', tags: ['brand'],
        body: 'Wide brand banner showing the wordmark "{brand}" in {style}, ornamental flourish, single accent color, cream backdrop.' },
    { id: 'img-lookbook', kind: 'image', name: 'Fashion Lookbook', blurb: 'Lookbook frame', tags: ['fashion'],
        body: 'Fashion lookbook frame of {garment}, daylight, paper backdrop, model gaze off-camera, narrow color story.' },
    // Video
    { id: 'vid-hero-loop', kind: 'video', name: 'Hero Loop', blurb: '4-sec product loop', tags: ['hero', 'loop'],
        body: '4-second seamless loop of {product} rotating slowly on a soft pedestal, studio gradient, gentle gleam, subtle particles.' },
    { id: 'vid-slowmo', kind: 'video', name: 'Slow-mo Pour', blurb: 'Liquid slow motion', tags: ['slowmo', 'food'],
        body: 'Slow-motion pour of {liquid} into a glass, droplets, light catching the stream, dark velvet backdrop.' },
    { id: 'vid-walkthrough', kind: 'video', name: 'Product Walkthrough', blurb: 'Camera dolly walkthrough', tags: ['walkthrough'],
        body: 'Smooth dolly camera walking through {space}, eye-level, soft handheld feel, golden-hour key light.' },
    { id: 'vid-typography', kind: 'video', name: 'Kinetic Type', blurb: 'Type animates in', tags: ['type', 'kinetic'],
        body: 'Kinetic typography: the phrase "{phrase}" animates in word by word with a soft scale-up, subtle drop shadow, paper backdrop.' },
    { id: 'vid-launch-tease', kind: 'video', name: 'Launch Teaser', blurb: '8-sec hype teaser', tags: ['teaser'],
        body: '8-second teaser: macro shots of {product} cut to a beat, ending on bold logo reveal, anamorphic flares.' },
    { id: 'vid-explainer-bg', kind: 'video', name: 'Explainer Backplate', blurb: 'Looping abstract bg', tags: ['background'],
        body: 'Looping abstract backplate suitable for screencast voiceover: large soft gradient blobs drifting, no text or focal subject.' },
    { id: 'vid-app-demo', kind: 'video', name: 'App Demo Clip', blurb: 'Phone-in-hand UI demo', tags: ['demo'],
        body: 'Hand holding phone, screen demonstrates {flow}, calm pace, single-take feel, neutral backdrop.' },
    { id: 'vid-news-style', kind: 'video', name: 'News-style Lower Third', blurb: 'Breaking-news lower third', tags: ['news'],
        body: 'News-style lower third with title "{title}" and sub "{sub}" sliding in from the left, subtle grid texture, restrained palette.' },
    { id: 'vid-mascot-wave', kind: 'video', name: 'Mascot Wave', blurb: 'Mascot greeting loop', tags: ['mascot'],
        body: 'Friendly 2D mascot {character} waving for 3 seconds in a perfect loop, soft outline, two-color shading.' },
    { id: 'vid-time-lapse', kind: 'video', name: 'Time-lapse', blurb: 'Sky time-lapse', tags: ['timelapse'],
        body: 'Time-lapse of {scene} from dawn to dusk, fixed camera, accelerated cloud motion, color grade leaning teal.' },
    { id: 'vid-cycling-icons', kind: 'video', name: 'Icon Cycle', blurb: 'Icon cycling carousel', tags: ['icons'],
        body: 'Icons related to {theme} cycle through a fixed frame, snappy ease-out, subtle pop sound design hint, neutral backdrop.' },
    { id: 'vid-3d-spin', kind: 'video', name: '3D Object Spin', blurb: 'Turntable orbit', tags: ['3d', 'turntable'],
        body: 'Turntable orbit of a clean 3D render of {object}, soft HDRI light, micro-imperfections, infinite-loop friendly.' },
    { id: 'vid-stop-motion', kind: 'video', name: 'Stop-motion', blurb: 'Paper stop-motion', tags: ['stopmotion'],
        body: 'Paper stop-motion: {object} assembling itself layer by layer on craft paper, jittery feel, warm desk lamp.' },
    { id: 'vid-talking-head', kind: 'video', name: 'Talking Head Plate', blurb: 'Talking-head backplate', tags: ['talkinghead'],
        body: 'Empty 16:9 plate sized for a talking-head insert: simple three-color geometric backdrop, slow horizontal drift.' },
    { id: 'vid-launch-counter', kind: 'video', name: 'Countdown', blurb: 'Five-second countdown', tags: ['counter'],
        body: 'Five-second countdown 5→1, large display numerals, single-color background, mechanical type-in feel.' },
    { id: 'vid-pattern-loop', kind: 'video', name: 'Pattern Loop', blurb: 'Op-art repeating loop', tags: ['pattern'],
        body: 'Op-art geometric pattern that loops perfectly, two-tone, slowly shifting hue.' },
    { id: 'vid-launch-banner', kind: 'video', name: 'Banner Reveal', blurb: 'Banner unfurl', tags: ['banner'],
        body: 'Cloth banner with the words "{phrase}" unfurling over {bg}, slow-mo physics, dappled light.' },
    { id: 'vid-portrait-wind', kind: 'video', name: 'Portrait in Wind', blurb: 'Hair in slow wind', tags: ['portrait'],
        body: 'Editorial portrait of {subject} with hair moving slowly in soft fan-wind, eye contact, neutral wardrobe, paper backdrop.' },
    // Audio
    { id: 'aud-vo-elegant', kind: 'audio', name: 'Voice — Editorial', blurb: 'Calm narration', tags: ['voice', 'editorial'],
        body: 'Read this in a calm, mid-paced editorial voice with restrained warmth, no music: "{copy}"' },
    { id: 'aud-vo-energetic', kind: 'audio', name: 'Voice — Energetic', blurb: 'Upbeat ad read', tags: ['voice', 'energetic'],
        body: 'Read this with upbeat ad energy, slight smile in voice, clear consonants: "{copy}"' },
    { id: 'aud-vo-news', kind: 'audio', name: 'Voice — Newsroom', blurb: 'News anchor delivery', tags: ['voice', 'news'],
        body: 'Newsroom delivery, neutral, even pace, no music: "{copy}"' },
    { id: 'aud-vo-asmr', kind: 'audio', name: 'Voice — Whisper', blurb: 'Soft whisper read', tags: ['voice', 'asmr'],
        body: 'Hushed near-whisper, very close mic feel: "{copy}"' },
    { id: 'aud-jingle', kind: 'audio', name: 'Jingle — 4 seconds', blurb: 'Brand mnemonic', tags: ['music', 'mnemonic'],
        body: 'Generate a 4-second brand jingle: warm acoustic guitar, single sung word "{brand}", optimistic resolution.' },
    { id: 'aud-bed-corp', kind: 'audio', name: 'Music Bed — Corp', blurb: 'Bed for explainer', tags: ['music', 'bed'],
        body: '30-second under-bed music for explainer: gentle felt piano, soft pad, minimal percussion, no melody on top.' },
    { id: 'aud-bed-tech', kind: 'audio', name: 'Music Bed — Tech', blurb: 'Synthy bed', tags: ['music', 'bed'],
        body: '30-second under-bed: pulsing analog synth, restrained kick, optimistic lift, no vocals.' },
    { id: 'aud-sfx-click', kind: 'audio', name: 'SFX — UI Click', blurb: 'Single soft click', tags: ['sfx'],
        body: 'Single short, soft UI click for affirm action, ~80ms, no reverb.' },
    { id: 'aud-sfx-success', kind: 'audio', name: 'SFX — Success', blurb: 'Pleasant chime', tags: ['sfx'],
        body: 'Two-note rising chime, friendly, ~600ms, glassy timbre.' },
    { id: 'aud-podcast-intro', kind: 'audio', name: 'Podcast Intro', blurb: '6-sec podcast cold open', tags: ['music', 'voice'],
        body: '6-second podcast intro: warm pad, single piano motif, then voice "{title}" with show name "{show}".' },
    // Hyperframes (HTML→video keyframes)
    { id: 'hf-hero-zoom', kind: 'hyperframe', name: 'Hero Zoom', blurb: 'Subtle hero zoom', tags: ['hero', 'zoom'],
        body: 'Hyperframe brief: render {artifact} for 4 seconds with a subtle 1.0→1.04 zoom on the hero region, ease-out, 60fps target.' },
    { id: 'hf-callout', kind: 'hyperframe', name: 'Callout Pop', blurb: 'Callout label pop', tags: ['callout'],
        body: 'Hyperframe: pop a callout label "{label}" pointing to the {target} element, fade-in 200ms then settle.' },
    { id: 'hf-feature-loop', kind: 'hyperframe', name: 'Feature Tour', blurb: 'Auto-tour through features', tags: ['tour'],
        body: 'Hyperframe: pan camera left-to-right through the three feature blocks of {artifact}, dwell 0.8s on each, total 6s.' },
    { id: 'hf-counter', kind: 'hyperframe', name: 'Counter Tick', blurb: 'Counter tick-up', tags: ['counter'],
        body: 'Hyperframe: tick the {counter} from 0 to {target} over 2.4s with a snappy ease-out.' },
    { id: 'hf-scroll-deck', kind: 'hyperframe', name: 'Deck Auto-scroll', blurb: 'Slide-by-slide reveal', tags: ['deck'],
        body: 'Hyperframe: auto-advance the deck slide-by-slide every 1.6s; cross-fade transition, total length = slide_count × 1.6s.' },
    { id: 'hf-hover-states', kind: 'hyperframe', name: 'Hover States Demo', blurb: 'Cycle hover states', tags: ['states'],
        body: 'Hyperframe: cycle through the hover, focus, and pressed states of the primary CTA, dwelling 0.5s on each, total 2s.' },
    { id: 'hf-mobile-walk', kind: 'hyperframe', name: 'Mobile Walkthrough', blurb: 'Phone mock walkthrough', tags: ['mobile'],
        body: 'Hyperframe: phone mock walkthrough — animate between 3 mobile screens of {artifact}, slide transitions, total 5s.' },
    { id: 'hf-banner-shine', kind: 'hyperframe', name: 'Banner Shine', blurb: 'Logo shine sweep', tags: ['banner'],
        body: 'Hyperframe: a soft white shine sweeps across the {brand} wordmark over 1.4s, stops dead-center, holds 200ms.' },
    /* ─── Image — extra ─── */
    { id: 'img-bw-doc', kind: 'image', name: 'Documentary B&W', blurb: 'Black & white documentary frame', tags: ['photo', 'bw'],
        body: 'Black-and-white documentary photograph of {subject}, deep blacks, generous mid-tones, available light only, slight grain.' },
    { id: 'img-tilt-shift', kind: 'image', name: 'Tilt-shift City', blurb: 'Miniature-style city scene', tags: ['photo'],
        body: 'Tilt-shift photo of {city} from above, miniature feel, vivid color, narrow band of focus across the centre.' },
    { id: 'img-collage', kind: 'image', name: 'Paper Collage', blurb: 'Cut-paper collage', tags: ['art'],
        body: 'Cut-paper collage about {topic}, torn edges, soft drop shadows, three-color palette, large negative spaces.' },
    { id: 'img-isometric-room', kind: 'image', name: 'Isometric Room', blurb: '3D room scene', tags: ['3d', 'isometric'],
        body: 'Isometric soft-3D room depicting {scene}, pastel materials, restrained palette, no people, no text.' },
    { id: 'img-vintage-ad', kind: 'image', name: 'Vintage Ad', blurb: 'Mid-century print ad', tags: ['retro'],
        body: 'Mid-century print advertisement for {product}, hand-lettered headline, two-color halftone illustration, paper texture.' },
    { id: 'img-cinema-poster', kind: 'image', name: 'Cinema Poster', blurb: 'Film one-sheet', tags: ['poster'],
        body: 'Film one-sheet poster for "{title}" — large display title, single hero figure, restrained palette, festival laurels at the bottom.' },
    { id: 'img-minimal-still', kind: 'image', name: 'Minimal Still Life', blurb: 'Quiet still-life', tags: ['stillife'],
        body: 'Minimal still life: a single {object} on a smooth surface, daylight, generous space, soft contact shadow.' },
    { id: 'img-product-explode', kind: 'image', name: 'Product Exploded', blurb: 'Exploded product diagram', tags: ['product', 'diagram'],
        body: 'Exploded view of {product}, components spaced apart, technical-illustration line art over a soft gradient backdrop, faint dimension lines.' },
    { id: 'img-mood-board', kind: 'image', name: 'Mood Board', blurb: 'Tonal mood board grid', tags: ['mood'],
        body: 'Mood-board grid of {n} swatches and textures evoking {feeling}, no copy, generous margins, paper-stock backdrop.' },
    { id: 'img-character-sheet', kind: 'image', name: 'Character Sheet', blurb: 'Three-quarter character study', tags: ['character'],
        body: 'Three-quarter character study of {character}, calm lighting, neutral backdrop, model-sheet poses on the right side.' },
    { id: 'img-space-station', kind: 'image', name: 'Space Station', blurb: 'Hard sci-fi exterior', tags: ['scifi'],
        body: 'Exterior of a hard-sci-fi space station orbiting {planet}, photorealistic, narrow color palette, soft starlight, no UI overlays.' },
    { id: 'img-microscopic', kind: 'image', name: 'Microscopic', blurb: 'Cells under microscope', tags: ['science'],
        body: 'Microscopic frame of {sample} under stained light, electric blues and pinks, ultra-shallow depth of field.' },
    /* ─── Video — extra ─── */
    { id: 'vid-product-spin-2', kind: 'video', name: 'Product Orbit', blurb: '12s product orbit', tags: ['turntable'],
        body: '12-second slow orbit around {product}, gimbal-smooth, soft white cyc, micro-imperfections in materials.' },
    { id: 'vid-handwriting', kind: 'video', name: 'Handwriting Reveal', blurb: 'Handwritten reveal', tags: ['handwriting'],
        body: 'Hand draws the phrase "{phrase}" in ink on cream paper, ~6 seconds, single take, top-down camera.' },
    { id: 'vid-paint-strokes', kind: 'video', name: 'Paint Strokes', blurb: 'Brushwork buildup', tags: ['art'],
        body: 'A brush builds an abstract painting of {subject} stroke by stroke over 8 seconds, paper visible underneath, single warm light.' },
    { id: 'vid-snowfall', kind: 'video', name: 'Snowfall Loop', blurb: 'Slow snow loop', tags: ['atmospheric'],
        body: 'Loopable shot of soft snowfall in front of a streetlamp, blue-hour light, ~6 seconds.' },
    { id: 'vid-firefly', kind: 'video', name: 'Fireflies', blurb: 'Firefly atmospheric loop', tags: ['atmospheric'],
        body: '4-second atmospheric loop of fireflies drifting over {meadow}, low key light, deep cyan grade.' },
    { id: 'vid-app-flow', kind: 'video', name: 'App Flow Sequence', blurb: 'App user flow demo', tags: ['demo'],
        body: 'Linear walk through the user flow {flow} on a phone — 3 phone shots cross-cut with finger-tap inserts. 12 seconds.' },
    { id: 'vid-news-broll', kind: 'video', name: 'News B-roll', blurb: 'B-roll for news segment', tags: ['news'],
        body: 'Three 4-second B-roll clips for a news segment about {topic}: wide, medium, detail. Neutral grade, no music.' },
    { id: 'vid-launch-stinger', kind: 'video', name: 'Stinger', blurb: '1.6s logo stinger', tags: ['stinger'],
        body: '1.6-second logo stinger for "{brand}": shape-form-in, single dwell, snap to wordmark, restrained sound design.' },
    { id: 'vid-podcast-vid', kind: 'video', name: 'Podcast Visualizer', blurb: 'Audio-reactive bars', tags: ['music'],
        body: 'Audio-reactive bar visualizer for a podcast episode of {show}, single accent color, looping infinitely.' },
    { id: 'vid-portrait-wind-2', kind: 'video', name: 'Linen in Wind', blurb: 'Linen flag in slow wind', tags: ['atmospheric'],
        body: 'Loopable 6-second shot of a beige linen flag rippling in slow wind against a clear sky, late afternoon.' },
    /* ─── Audio — extra ─── */
    { id: 'aud-vo-warm', kind: 'audio', name: 'Voice — Warm', blurb: 'Warm honest read', tags: ['voice'],
        body: 'Warm honest read, like talking to a friend, no music: "{copy}"' },
    { id: 'aud-vo-mid-atlantic', kind: 'audio', name: 'Voice — Mid-Atlantic', blurb: 'Mid-Atlantic accent', tags: ['voice'],
        body: 'Mid-Atlantic accent, slow tempo, high diction, no music: "{copy}"' },
    { id: 'aud-bed-cinematic', kind: 'audio', name: 'Music Bed — Cinematic', blurb: 'Cinematic underscore', tags: ['music'],
        body: '20-second cinematic underscore: low cellos, slow build, single piano motif, restrained reverb, no percussion.' },
    { id: 'aud-bed-acoustic', kind: 'audio', name: 'Music Bed — Acoustic', blurb: 'Acoustic guitar bed', tags: ['music'],
        body: '30-second acoustic-guitar bed in C major, gentle finger-picking, light shaker, optimistic.' },
    { id: 'aud-sfx-error', kind: 'audio', name: 'SFX — Error', blurb: 'Soft error tone', tags: ['sfx'],
        body: 'Soft, low descending two-note error tone, ~400ms, glassy timbre, no harshness.' },
    { id: 'aud-sfx-notify', kind: 'audio', name: 'SFX — Notify', blurb: 'Subtle notification', tags: ['sfx'],
        body: 'Subtle notification chime, single bell, ~300ms, mid-treble, friendly.' },
    { id: 'aud-radio-bumper', kind: 'audio', name: 'Radio Bumper', blurb: '8-sec radio bumper', tags: ['music', 'voice'],
        body: '8-second radio bumper for "{show}": short funk loop, voice tag at the end with the show name.' },
    /* ─── HyperFrame — extra ─── */
    { id: 'hf-fade-loop', kind: 'hyperframe', name: 'Cross-fade Loop', blurb: 'Cross-fade between two states', tags: ['loop'],
        body: 'Hyperframe: cross-fade between {stateA} and {stateB} of the artifact every 2 seconds, ease-in-out, total 8 seconds, perfect loop.' },
    { id: 'hf-callout-strip', kind: 'hyperframe', name: 'Feature Callouts', blurb: 'Animate feature callouts', tags: ['callout'],
        body: 'Hyperframe: pop callout labels in sequence over each feature card — fade-up 200ms, dwell 1.2s, total = (n*1.4s).' },
    { id: 'hf-cursor-tour', kind: 'hyperframe', name: 'Cursor Tour', blurb: 'Animated cursor walkthrough', tags: ['demo'],
        body: 'Hyperframe: an animated cursor moves between the three primary CTAs and lingers 0.6s on each; total 4s.' },
    { id: 'hf-typewriter', kind: 'hyperframe', name: 'Typewriter Heading', blurb: 'Type the headline', tags: ['type'],
        body: 'Hyperframe: typewriter-style reveal of the H1 headline at 28 chars/second, blinking caret, then settle.' },
    { id: 'hf-night-mode', kind: 'hyperframe', name: 'Day → Night', blurb: 'Theme transition', tags: ['theme'],
        body: 'Hyperframe: smoothly transition the artifact from light to dark theme over 2 seconds, ease-out, no harsh flash.' },
    { id: 'hf-side-tabs', kind: 'hyperframe', name: 'Tab Cycle', blurb: 'Cycle tabbed content', tags: ['ui'],
        body: 'Hyperframe: cycle through {n} tabbed sections of the artifact every 2 seconds, slide content from the right.' },
];
/* ─── VISUAL DIRECTIONS ───────────────────────────────────────────────── */
const visualDirections = [
    { id: 'vd-editorial', name: 'Editorial Quiet', vibe: 'Long-form, paper, restraint', font: 'Instrument Serif / Inter',
        swatches: ['oklch(0.97 0.02 80)', 'oklch(0.92 0.03 80)', 'oklch(0.20 0.02 60)', 'oklch(0.60 0.16 30)'],
        tagline: 'Newspaper newsroom calm. Display serif. Generous margins.' },
    { id: 'vd-vivid', name: 'Vivid Burst', vibe: 'Big color, big type, hopeful', font: 'Geist / Inter',
        swatches: ['oklch(0.16 0.04 280)', 'oklch(0.74 0.20 320)', 'oklch(0.78 0.18 200)', 'oklch(0.96 0.02 0)'],
        tagline: 'Loud gradients, fearless type, a touch of the future.' },
    { id: 'vd-utility', name: 'Tactical Utility', vibe: 'Mono, dense, precise', font: 'JetBrains Mono / Inter',
        swatches: ['oklch(0.14 0.01 200)', 'oklch(0.22 0.01 200)', 'oklch(0.72 0.16 145)', 'oklch(0.92 0.02 200)'],
        tagline: 'Reads like a terminal. Builds like a tool.' },
    { id: 'vd-warm', name: 'Warm Welcome', vibe: 'Friendly, ember, soft', font: 'Inter / Fraunces',
        swatches: ['oklch(0.18 0.02 264)', 'oklch(0.74 0.18 50)', 'oklch(0.62 0.22 36)', 'oklch(0.96 0.01 80)'],
        tagline: 'Hand on the shoulder. Light on the eyes.' },
    { id: 'vd-clinical', name: 'Clinical Clarity', vibe: 'White, blue, no flourish', font: 'Inter / Inter',
        swatches: ['oklch(0.97 0.01 240)', 'oklch(0.92 0.02 240)', 'oklch(0.58 0.18 250)', 'oklch(0.18 0.02 240)'],
        tagline: 'Quiet. Trustworthy. Indifferent to fashion.' },
    { id: 'vd-brutalist', name: 'Brutalist Raw', vibe: 'Exposed structure, no decoration', font: 'JetBrains Mono / Inter',
        swatches: ['oklch(0.96 0.00 0)', 'oklch(0.10 0.00 0)', 'oklch(0.50 0.00 0)', 'oklch(0.70 0.20 12)'],
        tagline: 'Borders visible. Grid exposed. Function over form.' },
    { id: 'vd-luxury', name: 'Quiet Luxury', vibe: 'Restrained opulence, serif, space', font: 'Fraunces / Inter',
        swatches: ['oklch(0.10 0.02 60)', 'oklch(0.18 0.03 60)', 'oklch(0.75 0.14 70)', 'oklch(0.95 0.02 60)'],
        tagline: 'Whisper, never shout. Gold is earned, not applied.' },
    { id: 'vd-playful', name: 'Playful Pop', vibe: 'Rounded, bouncy, saturated', font: 'Inter / Inter',
        swatches: ['oklch(0.97 0.02 280)', 'oklch(0.72 0.22 320)', 'oklch(0.78 0.20 145)', 'oklch(0.82 0.18 80)'],
        tagline: 'Rounded corners, generous padding, colors that smile.' },
    { id: 'vd-swiss', name: 'Swiss Grid', vibe: 'International typographic style', font: 'Inter / Inter',
        swatches: ['oklch(0.98 0.00 0)', 'oklch(0.10 0.00 0)', 'oklch(0.55 0.22 12)', 'oklch(0.70 0.00 0)'],
        tagline: 'Helvetica spirit. Rigid grid. Asymmetric balance.' },
    { id: 'vd-organic', name: 'Organic Flow', vibe: 'Soft curves, natural palette', font: 'Fraunces / Inter',
        swatches: ['oklch(0.95 0.04 130)', 'oklch(0.88 0.06 100)', 'oklch(0.50 0.12 145)', 'oklch(0.30 0.06 80)'],
        tagline: 'Rounded shapes, earth tones, breathing room.' },
    { id: 'vd-retro', name: 'Retro Analog', vibe: 'Vintage print, halftone, warm', font: 'Instrument Serif / Inter',
        swatches: ['oklch(0.93 0.06 60)', 'oklch(0.65 0.18 25)', 'oklch(0.45 0.14 200)', 'oklch(0.25 0.04 60)'],
        tagline: 'Halftone grain. Offset registration. Ink on newsprint.' },
    { id: 'vd-futurist', name: 'Futurist Glow', vibe: 'Dark glass, neon accents, depth', font: 'Geist / Inter',
        swatches: ['oklch(0.08 0.02 260)', 'oklch(0.14 0.04 260)', 'oklch(0.72 0.24 195)', 'oklch(0.78 0.22 320)'],
        tagline: 'Glass panels, neon edges, depth through blur.' },
    { id: 'vd-japandi', name: 'Japandi Calm', vibe: 'Wabi-sabi meets Scandinavian', font: 'Inter / Fraunces',
        swatches: ['oklch(0.94 0.02 80)', 'oklch(0.86 0.04 60)', 'oklch(0.40 0.06 80)', 'oklch(0.60 0.08 145)'],
        tagline: 'Imperfect beauty. Natural materials. Quiet function.' },
    { id: 'vd-maximalist', name: 'Maximalist Layer', vibe: 'Dense, layered, pattern-rich', font: 'Fraunces / Inter',
        swatches: ['oklch(0.16 0.06 320)', 'oklch(0.70 0.22 350)', 'oklch(0.75 0.20 60)', 'oklch(0.80 0.18 195)'],
        tagline: 'More is more. Patterns on patterns. Controlled chaos.' },
    { id: 'vd-dashboard', name: 'Data Dense', vibe: 'Information-rich, compact, clear', font: 'Inter / JetBrains Mono',
        swatches: ['oklch(0.12 0.02 240)', 'oklch(0.18 0.03 240)', 'oklch(0.65 0.18 195)', 'oklch(0.72 0.16 145)'],
        tagline: 'Every pixel earns its place. Dense but never cluttered.' },
    { id: 'vd-magazine', name: 'Magazine Spread', vibe: 'Editorial layout, pull quotes', font: 'Playfair Display / Inter',
        swatches: ['oklch(0.97 0.01 0)', 'oklch(0.10 0.01 0)', 'oklch(0.55 0.16 12)', 'oklch(0.85 0.04 60)'],
        tagline: 'Drop caps, pull quotes, full-bleed imagery, column rhythm.' },
    { id: 'vd-glassmorphism', name: 'Glass Layer', vibe: 'Frosted glass, blur, transparency', font: 'Inter / Inter',
        swatches: ['oklch(0.16 0.04 220)', 'oklch(0.24 0.06 220)', 'oklch(0.70 0.16 220)', 'oklch(0.90 0.04 220)'],
        tagline: 'Backdrop-blur, translucent panels, layered depth.' },
    { id: 'vd-neubrutalism', name: 'Neubrutalism', vibe: 'Thick borders, raw shadows, bold', font: 'Inter / Inter',
        swatches: ['oklch(0.95 0.04 80)', 'oklch(0.10 0.00 0)', 'oklch(0.75 0.22 80)', 'oklch(0.70 0.20 320)'],
        tagline: 'Thick black borders. Hard drop shadows. Unapologetic color.' },
];
/* ─── EXPORTS ─────────────────────────────────────────────────────────── */
export function listSkills() {
    return skills.map((s) => ({
        id: s.id, name: s.name, category: s.category, blurb: s.blurb, emoji: s.emoji,
    }));
}
export function getSkill(id) {
    return skills.find((s) => s.id === id);
}
export function listDesignSystems() {
    return systems.map((d) => ({
        id: d.id, name: d.name, vibe: d.vibe, swatches: d.swatches, font: d.font,
    }));
}
export function getDesignSystem(id) {
    return systems.find((d) => d.id === id);
}
export function listPromptTemplates() {
    return promptTemplates;
}
export function listVisualDirections() {
    return visualDirections;
}
